#!/sh
. functions

setup () {
	start_daemon
}

run () {
	echo "yq should be able to parse syndiag's stdout."
	"$SYNDIAG_EXEC" "$SYNDIAG_HOST" "$SYNDIAG_PORT" | yq '.' -

	gracefully_stop_daemon
}

cleanup () {
	forcefully_stop_daemon
}
