@startuml

title mtu1280 mode in IPv4

skinparam defaulttextalignment center

participant "syndiagd" as A
control "mtu1280 router" as M
participant "syndiag" as B

M (10)<- B: DF, PSH, len > 1280
M ->(10) B: **ICMP fragmentation required**
note over B: PMTU adjusted
M (10)<- B: DF, PSH, len == 1280
A (10)<- M: DF, PSH, len == 1280
M (10)<- B: DF, PSH, len < 1280
A (10)<- M: DF, PSH, len < 1280

note across: request finished

A ->(10) M: PSH, len > 1280
note over M: fragmentation
M ->(10) B: **IP fragment** == 1280
M ->(10) B: **IP fragment** < 1280

@enduml
